stages:
  - build
  - deploy

build:
  stage: build
  image: node:20-alpine
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  only:
    - main
    - stage

pages:
  stage: deploy
  image: alpine:latest
  script:
    - mv dist public
  artifacts:
    paths:
      - public/
  only:
    - main
    - stage
